project:
  type: website
  output-dir: .

website:
  title: "OUN VIKRETH"
  site-url: https://oun-vikreth.github.io/
  description: "Portfolio, projects, and CV of Oun Vikreth, Data Scientist and Credit Risk Modelling."
  navbar:
    logo: "statics/logo.gif"
    right:
      - about.qmd
      - cv.qmd
      - index.qmd
      - icon: github
        href: https://github.com/oun-vikreth
      - icon: LinkedIn
        href: https://www.linkedin.com/in/oun-vikreth/

format:
  html:
    theme: sandstone
    css: styles.css

metadata:
  robots: index, follow
